language: node_js
node_js:
- 6
- node
after_success:
- npm install -g coveralls
- coveralls < ./coverage/lcov.info
deploy:
  provider: npm
  email: n.halcyon@gmail.com
  api_key:
    secure: 6mG6ujqbDlBu0XmF5-NWjg
  on:
    tags: true
    branch: master