language: node_js
node_js:
- 12
- node
after_success:
- npm install -g coveralls
- coveralls < ./coverage/lcov.info
deploy:
  provider: npm
  email: n.halcyon@gmail.com
  api_key: 0e4aeacb-7b47-4d4c-9cfe-288a4428a019
  on:
    tags: true
    branch: master